### ISSUE TITLE
 RuntimeError - Can't find price for 

### ISSUE THREAD

**Issue by aaron-76** [stripe/example-mobile-backend#83]
he problem: when using this method I simply clicked on the purple icon and proceeded to enter my info and created a backendUrl to be used for my app. All works except when it comes to processing the payment as my inventory items(located in firebase) are not able to be retrieved. Therefore, when placing order I get this in swift: "Failed to create a Payment Intent: unknown"

After getting this error I examined the logs in Heroku and came across this: RuntimeError - Can't find price for Guacamole

so it seems that the payment isn't going through because it can not retrieve the price for this item.

Finally I figure I just add "Guacamole" => 2000 to the list above and run it.

SADLY this did not work. I have no prior experience with ruby but when I applied the above to the list I still got the same error: RuntimeError - Can't find price for Guacamole

I did basically what you commented above but it is unable to retrieve prices for items I add to the EMOJI_StORE

**Comment by davidme-stripe** [comment]
Hey @aaron-76,

It sounds like what you're doing should work. Are you sure you're pointing your client to the modified server? If you're running it off a Heroku instance, you may need to push your updated server.rb to Heroku. Would it be possible for you to share your code?

**Comment by aaron-76** [comment]
@davidme-stripe  by server.rb are you referring to the web.rb file? 

I have also asked this on STACK: https://stackoverflow.com/questions/60923360/how-do-i-add-inventory-items-via-ruby-heroku

The above link may reduce some redundancy so please take a look. As for the code I just added the item to the web.rb file in the EMOJI_STORE  section  and  I am editing the code on my end and using git add . git commit -m "updates" ** git push heroku master to upload it to heroku.  Do you need my code in my SWIFT file? 

btw I really appreciate your help...I have been spending a heavy amount on trying to solve this issue.

**Comment by davidme-stripe** [comment]
Someone on that StackOverflow link pointed out that the error indicates an extra space in your `"Guacamole"` string: Can you double-check in both web.rb and in your iOS app that it's `"Guacamole"` and not `"Guacamole "`?

**Comment by aaron-76** [comment]
that solved the issue!
